config/routes.rb
Rails.application.routes.draw do
  resources :todos do
    resources :articles 
    post "complete"
  end
  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :articles , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new

    @todo = Todo.where(id: params[:todo_id]).first
    article=Article.new
  end

  def create
    @todo = Todo.where(id: params[:todo_id]).first
    @article = @todo.articles.build(article_params)

    if @article.save
      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end

  def show
    @todo = Todo.where(id: params[:todo_id]).first
    @article = @todo.articles.find(params[:id])
  end

  def edit
    @todo = Todo.where(id: params[:todo_id]).first
    @article = @todo.articles.find(params[:id])
  end

  def update
    @todo = Todo.where(id: params[:todo_id]).first
    @article = @todo.articles.find(params[:id])
    if @article.update(article_params)
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def destroy
    @todo = Todo.where(id: params[:todo_id]).first
    @article = @todo.articles.find(params[:id])
    @article.destroy

    redirect_to todo_path(@todo)
  end


  private
  def article_params
    params.require(:article).permit(:title)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to @todo
    else
      render 'new'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_path
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def show
#    require 'pry'; binding.pry
    @todo = Todo.find(params[:id])
     @articles = @todo.articles
  end

  def update
    @todo  = Todo.find(params[:id])

    if @todo.update(todo_params)
      redirect_to @todo
    else
      render 'edit'
    end
  end

  def complete
    @todo = Todo.where(id: params[:todo_id]).first
    params[:articles_checkbox].each do |check|
      article_id = check
      @article = Article.find_by_id(article_id)
      @article.update_attribute(:is_done, true)
#      flash[:notice] = "Task completed"
    end
    redirect_to todo_path(@todo)
  end
  private
  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/articles/edit.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class ="navbar-brand">
        <strong>

          <div class="active">
            <%= link_to todos_path do  %>
              <div style="color:hsl(216, 80%, 50%);"><strong>   <span class="glyphicon glyphicon-home"></span>Home</strong></div><% end %>
          </div>
      </strong> </div>
    </div>

    <ul class="nav navbar-nav">
      <div class="navbar-text"> <strong><li><font size="3"> <%= link_to  todo_path(@todo) do %><%@todo.title%><%end%></font> </li><strong></div>
        </ul>
      </div>
    </nav>
    <div class="container col-xl-10 col-xl-offset-1" style="position:relative; top:100px;">

      <h1>Edit Task's title</h1>

      <%= form_with(model: [ @todo, @todo.articles.find(params[:id]) ], local: true) do |form| %>
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </p>

        <p>
          <%= form.submit %>
        </p>

      <% end %>
    </div>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: todo_articles_path, local: true do |form| %>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class ="navbar-brand"> 
          <strong>

            <div class="active">
              <%= link_to todos_path do  %>
                <div style="color:hsl(216, 80%, 50%);"><strong>   <span class="glyphicon glyphicon-home"></span>Home</strong></div><% end %>
            </div>
        </strong> </div>
      </div>

      <ul class="nav navbar-nav">
        <div class="navbar-text"> <strong><li><font size="3"> <%= link_to  todo_path(@todo) do %><%@todo.title%><%end%></font> </li><strong></div>
          </ul>
        </div>
      </nav>
      <div class="container col-xl-10 col-xl-offset-1" style="position:relative; top:100px;">
        <p>
          <h1 class="display-2">   <%= form.label :title %></h1><br>
          <%= form.text_field :title %>
        </p>

        <p>
          <%= form.submit %>
        </p>
      </div>
    <% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Status:</strong>
  <% if @article.is_done %>Completed<% else %>Pending<% end %>
</p>

<h4><%= link_to 'Back', todo_path(@todo) %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<%= form_with(model: @todo, local: true) do |form| %>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class ="navbar-brand">
          <strong>

            <div class="active">
              <%= link_to todos_path do  %>
                <div style="color:hsl(216, 80%, 50%);"><strong>   <span class="glyphicon glyphicon-home"></span>Home</strong></div><% end %>
            </div>
        </strong> </div>
      </div>
    </div>
  </nav>
  <div class="container col-xl-10 col-xl-offset-1" style="position:relative; top:100px;">
    <h1>Edit Todo's title</h1>
    <p>
      <h1 class="display-2">   <%= form.label :title %></h1><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  </div>

<% end %>

app/views/todos/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav" style="position: absolute;
        left: 50%;
        transform: translatex(-50%);">
        <div class="navbar-text"> <li><strong><h3 style="padding:0; margin:0;">To-Do list</h3></strong> </li></div>
      </ul>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to todos_path do  %>
              <div style="color:hsl(216, 80%, 50%);"><strong><h4>   <span class="glyphicon glyphicon-home"></span>Home</strong></h4></div><% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav ">
          <div class="navbar-text"> <li><h4><%= link_to 'New To-Do list', new_todo_path %></h4> </li></div>
        </ul>
      </div>
    </div>
  </nav>
  <div class="table-responsive" style=" position: relative; top: 100px;">
    <table class="table table-hover" style="text-align: center">
      <tr>
        <th style="text-align: center"><h3><strong>Title</strong></h3></th>
        <th colspan="3"></th>
      </tr>

      <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.title %></td>
          <td><%= link_to 'Show', todo_path(todo) %></td>
          <td><%= link_to  edit_todo_path(todo) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %></td>
      </td>
      <td><%= link_to  todo_path(todo),
        method: :delete,
        data: { confirm: 'Are you sure?' } do%>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </td>
  </tr>
<% end %>
</table>
</div></div>

app/views/todos/new.html.erb
<%= form_with scope: :todo, url: todos_path, local: true do |form| %>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class ="navbar-brand">
          <strong>

            <div class="active">
              <%= link_to todos_path do  %>
                <div style="color:hsl(216, 80%, 50%);"><strong>   <span class="glyphicon glyphicon-home"></span>Home</strong></div><% end %>
            </div>
        </strong> </div>
      </div>
    </div>
  </nav>
  <div class="container col-xl-10 col-xl-offset-1" style="position:relative; top:100px;">
    <p>
      <h1 class="display-2">   <%= form.label :title %></h1><br>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  </div>
<% end %>

app/views/todos/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="navbar-brand" style="position: absolute;
        left: 50%;
        transform: translatex(-50%);">
        <strong><%= @todo.title %></strong> </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to todos_path do  %>
              <div style="color:hsl(216, 80%, 50%);"><strong>   <span class="glyphicon glyphicon-home"></span>Home</strong></div><% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav">
          <div class="navbar-text"> <li><%= link_to 'New Task', new_todo_article_path(@todo) %> </li></div>
        </ul>
      </div>
    </div>
  </div>
</nav>
<div class="container-fluid">
  <div class="row">
    <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-xs-8">
      <div class="table-responsive" style=" position: relative; top: 100px;">

        <table class="table table-hover" style="text-align: center">
          <tr>
            <th style="text-align: center"><strong><h3>Task</h3></strong></th>
            <th colspan='3'></th>
          </tr>

          <% @articles.each do |article| %>
            <tr>
              <td><%= article.title %></td>
              <% if article.is_done != true %> <td><%= link_to  edit_todo_article_path(@todo, article) do  %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %></td><% else %><td></td><% end %>
          <!--<td><%= link_to 'Show', todo_article_path( @todo, article) %></td>-->

              <td><%= link_to todo_article_path(@todo, article), method: :delete, data: { confirm: 'Are you sure?' }  do  %>
                <span class="glyphicon glyphicon-trash">
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-xs-4">
    <div class="table-responsive" style=" position: relative; top: 127px;">
      <table class="table table-hover" style="text-align: center">
        <%= form_tag(todo_complete_path(@todo), :method => "post") do %>
          <% @articles.each do |article| %>
            <tr><td>
                <% if article.is_done %>
                  <%= check_box_tag "articles_checkbox[]", article.id , true , :disabled => true %>
                <% else %>
                  <%= check_box_tag "articles_checkbox[]", article.id %>
                <% end %></td></tr>
          <% end %>
          <div class="col-lg-offset-4">
          <%= submit_tag("Complete Tasks", class: "btn btn-lg btn-primary") %>
        <% end %></div>
      </table>
</div></div></div></div>